"""puzzles_table

Revision ID: a6d21e0f369b
Revises: 
Create Date: 2019-11-12 19:19:21.853716

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a6d21e0f369b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('puzzles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('puzzle', sa.String(length=81), nullable=True),
    sa.Column('difficulty', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_puzzles_difficulty'), 'puzzles', ['difficulty'], unique=False)
    op.create_index(op.f('ix_puzzles_puzzle'), 'puzzles', ['puzzle'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_puzzles_puzzle'), table_name='puzzles')
    op.drop_index(op.f('ix_puzzles_difficulty'), table_name='puzzles')
    op.drop_table('puzzles')
    # ### end Alembic commands ###
